# Generated by Django 4.0.6 on 2022-10-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='timenow',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
