# Generated by Django 4.0.6 on 2022-09-19 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encounter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkcontract', models.CharField(blank=True, max_length=200)),
                ('datenow', models.CharField(blank=True, max_length=200)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('latitude', models.CharField(blank=True, max_length=200)),
                ('longitude', models.CharField(blank=True, max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkcontract', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
