# Generated by Django 4.0.6 on 2022-10-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounter', '0002_checkcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkcontract',
            name='timenow',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='encounter',
            name='timenow',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
