# Generated by Django 4.1 on 2022-10-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='datenow',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='timenow',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
