# Generated by Django 4.0.6 on 2022-10-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salestotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='timenow',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salestotal',
            name='timenow',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
